language: php
os: linux
dist: trusty
services:
  - mongodb
env:
  - PHPUNIT_VERSION=7.5

jobs:
  fast_finish: true
  allow_failures:
    - php: "nightly"
  include:
    - php: "5.3"
      dist: precise
      env:
      - PHPUNIT_VERSION=4.8
    - php: "5.4"
      env:
      - PHPUNIT_VERSION=4.8
    - php: "5.5"
      env:
      - PHPUNIT_VERSION=4.8
    - php: "5.6"
      env:
      - PHPUNIT_VERSION=5.7
    - php: "7.0"
      env:
      - PHPUNIT_VERSION=6.5
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4"
    - php: "nightly"

    # without perftools/xhgui-collector
    - php: "5.3"
      dist: precise
      env:
      - PHPUNIT_VERSION=4.8
      - XHGUI_COLLECTOR=false
    - php: "5.4"
      env:
      - PHPUNIT_VERSION=4.8
      - XHGUI_COLLECTOR=false
    - php: "5.5"
      env:
      - PHPUNIT_VERSION=4.8
      - XHGUI_COLLECTOR=false
    - php: "5.6"
      env:
      - PHPUNIT_VERSION=5.7
      - XHGUI_COLLECTOR=false
    - php: "7.0"
      env:
      - PHPUNIT_VERSION=6.5
      - XHGUI_COLLECTOR=false
    - php: "7.1"
      env:
      - XHGUI_COLLECTOR=false
    - php: "7.2"
      env:
      - XHGUI_COLLECTOR=false
    - php: "7.3"
      env:
      - XHGUI_COLLECTOR=false
    - php: "7.4"
      env:
      - XHGUI_COLLECTOR=false
    - php: "nightly"
      env:
      - XHGUI_COLLECTOR=false

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer config preferred-install dist
  - composer remove --dev alcaeus/mongo-php-adapter --no-update
  - composer install
  - composer require --dev phpunit/phpunit:^$PHPUNIT_VERSION
  - ./install-extensions.sh || true
  - if [ "$XHGUI_COLLECTOR" = "false" ]; then composer remove --dev perftools/xhgui-collector; fi

script:
  - vendor/bin/phpunit --version
  - vendor/bin/phpunit --verbose

# vim:ts=2:sw=2:et
